name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - name: Update sponsors
        run: pnpm dlx sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: barbapapazes

      - name: Commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          message: "chore: update sponsors"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
